services:
  hrms_next_frontent_main:
    # container_name: hrms_frontend
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NEXT_APP_BASE_URL: ${NEXT_APP_BASE_URL}
    restart: always
    ports:
      - "3070:3000"
    networks:
      - hrms_network

networks:
  hrms_network:
